export const LOGIN_USER = 'login_user'
export const REGISTER_USER = 'register_user'
export const AUTH_USER = 'auth_user'
export const MAKE_ROOM = 'make_room'
export const GET_ROOM = 'get_room'
export const JOIN_ROOM = 'join_room'